### ISSUE TITLE
Design UI - choose train station screen

### ISSUE THREAD

**Issue by lesslieli** [LotusGrads/IamLateForTheTrain#10]

**Comment by lesslieli** [comment]
**User interaction:** user interacts with search bar by pressing on search bar, keyboard appears allowing users to input train station name, user confirms input, train station option should appear in the body (if user input is valid). User can then select the option to confirm their desired train station.

**Comment by lilianlyx** [comment]
![First Draft](https://user-images.githubusercontent.com/126132340/229033772-fa51df5e-1ad4-441b-9461-67eda149cfa5.png)
