### ISSUE TITLE
Design UI - select train line

### ISSUE THREAD

**Issue by lesslieli** [LotusGrads/IamLateForTheTrain#11]

**Comment by lesslieli** [comment]
depends on #10

**Comment by issytuttle** [comment]
Once train station is selected, upcoming train departures is shown, including which train line and how far away the train departure is from current time. After selecting desired train line, you will be notified whether you would make the train from your current destination or whether you should select another train line. By selecting a train line that gives you enough time to make the train station, the user will then be notified if they are not walking fast enough to make their train departure.
